// words.js - MR TYPE Professional Word Pools
// Extensive word collections for all modes with 1000+ words each

const WORD_POOLS = {
  en: [
    // Basic words (1-3 letters)
    "a","an","as","at","be","by","do","go","he","if","in","is","it","me","my","no","of","on","or","so",
    "to","up","us","we","all","and","any","are","but","can","day","for","get","had","has","her","him",
    "his","how","its","may","not","now","off","old","one","out","own","see","she","the","two","use",
    "was","way","who","why","you","about","above","after","again","among","area","back","ball","been",
    "before","below","between","both","call","came","come","could","dark","down","each","even","every",
    "find","first","from","give","good","have","here","into","just","know","last","left","like","line",
    "little","live","long","look","made","make","many","more","most","much","must","name","need","never",
    "new","next","night","noon","none","not","off","often","old","on","once","only","open","or","order",
    "other","out","over","own","part","people","place","point","put","right","same","say","see","she",
    "should","since","small","so","some","still","such","take","tell","than","that","the","their","them",
    "then","there","these","they","thing","think","this","those","through","time","to","too","two","under",
    "up","upon","us","use","very","want","was","way","we","well","went","were","what","when","where",
    "which","while","who","will","with","word","work","would","write","year","you","your",
    // Intermediate words (4-6 letters)
    "about","above","across","act","active","activity","actually","add","address","after","again",
    "against","age","agency","agent","ago","agree","ahead","allow","almost","alone","along","already",
    "also","although","always","american","among","amount","analysis","and","animal","another","answer",
    "any","anything","appear","apply","approach","area","argue","around","arrive","art","article",
    "artist","ask","assume","attack","attention","attorney","audience","author","authority","available",
    "avoid","away","baby","back","ball","bank","bar","base","beat","beautiful","become","bed","before",
    "begin","behavior","behind","believe","benefit","best","better","between","beyond","big","bill",
    "billion","bit","black","blood","blue","board","body","book","born","both","box","boy","break",
    "bring","brother","budget","build","building","business","but","buy","by","call","camera","campaign",
    "can","cancer","candidate","capital","car","card","care","career","carry","case","catch","cause",
    "cell","center","central","century","certain","certainly","chair","challenge","chance","change",
    "character","charge","check","child","choice","choose","church","citizen","city","civil","claim",
    "class","clear","clearly","close","coach","cold","collection","college","color","come","commercial",
    "common","community","company","compare","computer","concern","condition","conference","congress",
    "consider","consumer","contain","continue","control","cost","could","country","couple","course",
    "court","cover","create","crime","cultural","culture","cup","current","customer","cut","dark","data",
    "daughter","day","dead","deal","death","debate","decade","decide","decision","deep","defense",
    "degree","democrat","democratic","describe","design","despite","detail","determine","develop",
    "development","die","difference","different","difficult","dinner","direction","director","discover",
    "discuss","discussion","disease","do","doctor","dog","door","down","draw","dream","drive","drop",
    "drug","during","each","early","east","easy","eat","economic","economy","edge","education",
    "effect","efficient","effort","eight","either","election","else","employee","end","energy",
    "enjoy","enough","enter","entire","environment","environmental","especially","establish","even",
    "evening","event","ever","every","everybody","everyone","everything","evidence","exactly","example",
    "executive","exist","expect","experience","expert","explain","eye","face","fact","factor","fail",
    "fall","family","far","fast","father","fear","federal","feel","feeling","few","field","fight",
    "figure","fill","film","final","finally","financial","find","fine","finger","finish","fire","firm",
    "first","fish","five","floor","fly","focus","follow","food","foot","for","force","foreign","forget",
    "form","former","forward","four","free","friend","from","front","full","fund","future","game",
    "garden","gas","general","generation","get","girl","give","glass","go","goal","good","government",
    "great","green","ground","group","grow","growth","guess","gun","guy","hair","half","hand","hang",
    "happen","happy","hard","have","head","health","hear","heart","heat","heavy","help","her","here",
    "herself","high","him","himself","his","history","hit","hold","home","hope","hospital","hot","hotel",
    "hour","house","how","however","huge","human","hundred","husband","i","idea","identify","if","image",
    "imagine","impact","important","improve","in","include","including","increase","indeed","indicate",
    "individual","industry","information","inside","instead","institution","interest","interesting",
    "international","interview","into","investment","involve","issue","it","item","its","itself","job",
    "join","just","keep","key","kid","kill","kind","kitchen","know","knowledge","land","language","large",
    "last","late","later","laugh","law","lawyer","lay","lead","leader","learn","least","leave","left",
    "leg","legal","less","let","letter","level","lie","life","light","like","likely","line","list","listen",
    "little","live","local","long","look","lose","loss","lot","love","low","lunch","machine","magazine",
    "main","maintain","major","majority","make","man","manage","management","manager","many","market",
    "marriage","material","matter","may","maybe","me","mean","measure","media","medical","meet","meeting",
    "member","memory","mention","message","method","middle","might","mile","military","million","mind",
    "minute","miss","mission","model","modern","moment","money","month","more","morning","most","mother",
    "mouth","move","movement","movie","much","music","must","my","name","nation","national","natural",
    "nature","near","nearly","necessary","need","network","never","new","news","newspaper","next","nice",
    "night","no","none","nor","north","not","note","nothing","notice","now","number","occur","of","off",
    "offer","office","officer","official","often","oh","oil","ok","old","on","once","one","only","onto",
    "open","operation","opportunity","option","or","order","organization","other","others","our","out",
    "outside","over","own","owner","page","pain","painting","paper","parent","part","participant",
    "particular","particularly","party","pass","past","patient","pattern","pay","peace","people","per",
    "perform","performance","perhaps","period","person","personal","phone","physical","pick","picture",
    "piece","place","plan","plant","play","player","point","police","policy","political","poor","popular",
    "population","position","positive","possible","post","power","practice","prepare","present","president",
    "pressure","pretty","prevent","price","private","probably","problem","process","produce","product",
    "production","professional","professor","program","project","property","protect","prove","provide",
    "public","pull","purpose","push","put","quality","question","quickly","quite","race","radio","raise",
    "range","rate","rather","reach","read","ready","real","reality","really","reason","receive","recent",
    "recently","recognize","record","red","reduce","reflect","region","relate","relationship","religious",
    "remain","remember","remove","report","represent","Republican","require","research","resource",
    "respond","response","responsibility","rest","result","return","reveal","rich","right","rise","risk",
    "road","rock","role","room","rule","run","safe","same","save","say","scene","school","science",
    "scientist","score","sea","season","seat","second","section","security","see","seek","seem","sell",
    "send","senior","sense","series","serious","serve","service","set","seven","several","sexual","shake",
    "share","she","shoot","short","shot","should","shoulder","show","side","sign","significant","similar",
    "simple","simply","since","sing","single","sister","sit","situation","six","size","skill","skin",
    "small","smile","so","social","society","soldier","some","somebody","someone","something","sometimes",
    "son","song","soon","sort","sound","source","south","southern","space","speak","special","specific",
    "speech","spend","sport","spring","staff","stage","stand","standard","star","start","state","station",
    "stay","step","still","stock","stop","store","story","straight","strange","strategy","street",
    "strength","strike","strong","structure","student","study","stuff","style","subject","success",
    "successful","such","suddenly","suffer","suggest","summer","sun","supply","support","sure","surface",
    "surprise","system","table","take","talk","task","tax","tea","teach","teacher","team","technology",
    "television","tell","ten","tend","term","test","than","thank","that","the","their","them","themselves",
    "then","theory","there","these","they","thing","think","third","thirty","this","those","though",
    "thought","thousand","three","through","throughout","throw","thus","time","to","today","together",
    "tomorrow","tone","too","top","total","tough","toward","town","trade","traditional","travel","treat",
    "treatment","tree","trial","trip","trouble","true","truth","try","turn","tv","two","type","under",
    "understand","unit","until","up","upon","us","use","usually","value","various","very","victim","view",
    "violence","visit","voice","wait","walk","wall","want","war","watch","water","way","we","weapon",
    "wear","week","weight","well","west","western","what","whatever","when","where","whether","which",
    "while","white","who","whole","whom","whose","why","wide","wife","will","win","wind","window","wish",
    "with","within","without","woman","wonder","word","work","worker","world","worry","would","write",
    "writer","wrong","yard","yeah","year","yes","yet","you","young","your","yourself"
  ],

  uz: [
    "va","bu","bir","ham","bilan","uchun","edi","deb","shu","men","sen","u","biz","siz","ular","nima",
    "qanday","qayerda","qachon","kim","nega","shunday","yana","endi","mana","bor","yoq","kerak","mumkin",
    "yaxshi","yomon","katta","kichik","yangi","eski","birinchi","oxirgi","hamma","hech","faqat","agar",
    "chunki","lekin","yoki","hatto","oldin","keyin","hozir","doim","bazan","tez","sekin","oson","qiyin",
    "ish","soz","til","dunyo","odam","bola","ota","ona","dost","maktab","kitob","suv","non","uy","vaqt",
    "kun","oy","yil","soat","pul","olish","berish","kelish","ketish","korish","bilish","aytish","yashamoq",
    "sevmoq","kulmoq","ovqat","olma","anor","uzum","nonushta","tushlik","kechki","deraza","eshik","bog",
    "gul","daraxt","qush","baliq","mushuk","kuchuk","ot","qoy","sigir","sher","yolbars","yaxshilik",
    "gozallik","boylik","salomatlik","baxt","dostlik","hurmat","ozodlik","tinchlik","adolat","aql","bilim",
    "tajriba","jasurlik","halollik","mehnat","rohat","harakat","galaba","kuch","imkoniyat","natija","sabab",
    "oqibat","juda","nihoyat","yol","manzil","masofa","yaqin","uzoq","issiq","sovuq","yorug","ogir","yengil",
    "qattiq","keng","tor","chuqur","toza","iflos","shirin","achchiq","mazali","sokin","soglom","kasal",
    "kuchli","zaif","boy","baxtli","aqlli","chiroyli","baland","past","semiz","ozgin","tezkor","qadimgi",
    "zamonaviy","oddiy","murakkab","aniq","ravshan","tushunarli","maxfiy","ochiq","yopiq","erkin","tayyor",
    "pishgan","yosh","qari","tabiiy","haqiqiy","soxta","tori","egri","tekis","butun","singan","silliq",
    "nozik","qalin","ingichka","qimmat","arzon","kup","oz","barcha","qilmoq","etmoq","bolmoq","kelmoq",
    "ketmoq","bormoq","turmoq","yotmoq","otirmoq","yurmoq","chopmoq","uchmoq","suzmoq","yemoq","ichmoq",
    "olmoq","aytmoq","gapirmoq","yozmoq","oqimoq","ishlamoq","oynamoq","kuylamoq","raqsga","tushmoq",
    "kutmoq","topmoq","yetmoq","bermoq","olmoq","sotmoq","sotib","olmoq","topshirmoq","yubormoq",
    "kirmoq","chiqmoq","tushunmoq","anglamoq","his","qilmoq","sezmoq","hissiyot","quvonch","gazab",
    "qayguriq","tushkunlik","umid","ishonch","sevgi","nafrat","hasad","sabr","shukr","minnatdorlik",
    "hurmat","qadr","izzat","obro","nufuz","dovrug","shon","sharaf","fahm","idrok","zehn","aql","zakovat",
    "farosat","donishmand","alloma","olim","ustoz","murabbiy","shogird","izdosh","safdosh","hamkasb",
    "qardosh","birodar","singil","opa","aka","tog'a","amaki","xola","amma","bobom","buvi","nabira","chevar",
    "avlod","nasl","ajdod","zot","nasab","kelib","chiqish","ildiz","poya","shox","barg","gul","meva",
    "hosil","ekin","ziroat","dehqon","bogbon","chorvador","qoramol","parranda","mollama","xazon","qor",
    "yomgir","shamol","dovul","bo'ron","chaqmoq","momaqaldiroq","quyosh","oy","yulduz","osmon","fazo",
    "olam","koinot","sayyora","yer","suv","havo","olov","tuproq","tog","tosh","qum","chang","loy","balchiq",
    "daryo","ko'l","dengiz","okean","ariq","kanal","buloq","chashma","sharshara","vodiy","sahro","cho'l",
    "o'rmon","dasht","yaylov","qirlar","tepalik","qoyalar","g'or","mag'ara","boshpana","uy","joy","makon",
    "maskan","shelter","vatan","o'zbekiston","toshkent","samarqand","buxoro","xiva","qo'qon","andijon",
    "namangan","farg'ona","urganch","nukus","qarshi","termez","jizzax","sirdaryo","navoiy","guliston"
  ],

  ru: [
    "и","в","не","он","на","я","что","тот","быть","с","а","весь","это","как","она","по","но","они","к",
    "из","у","же","вы","за","бы","только","её","мне","было","вот","от","меня","ещё","нет","о","ему",
    "теперь","когда","даже","ну","вдруг","ли","если","уже","или","ни","под","над","со","все","мы","то",
    "да","ты","при","для","без","сам","люди","работа","время","место","год","слово","жизнь","день",
    "свой","другой","первый","новый","большой","знать","видеть","сказать","идти","думать","стать",
    "который","такой","где","тут","там","потому","этот","наш","мир","земля","вода","огонь","воздух",
    "солнце","луна","звезда","небо","ночь","дело","сила","рука","нога","дверь","окно","стол","книга",
    "деньги","путь","город","улица","страна","власть","закон","порядок","идея","мысль","чувство",
    "радость","боль","счастье","судьба","вера","надежда","любовь","смерть","воля","душа","тело","кровь",
    "сердце","разум","память","опыт","мечта","цель","результат","вопрос","ответ","помощь","совет","друг",
    "враг","гость","хозяин","муж","жена","ребёнок","сын","дочь","брат","сестра","отец","мать","семья",
    "дом","комната","хлеб","молоко","чай","кофе","сахар","соль","масло","рыба","мясо","фрукт","яблоко",
    "утро","вечер","сегодня","завтра","вчера","всегда","никогда","часто","редко","рано","поздно","быстро",
    "медленно","хорошо","плохо","красиво","громко","тихо","легко","трудно","просто","сложно","тепло",
    "холодно","жарко","дождь","снег","ветер","весна","лето","осень","зима","месяц","неделя","час","минута",
    "секунда","цвет","красный","синий","зелёный","жёлтый","белый","чёрный","серый","тёмный","светлый",
    "яркий","тусклый","блестящий","матовый","прозрачный","мутный","чистый","грязный","сухой","мокрый",
    "влажный","сырой","солёный","сладкий","кислый","горький","острый","пресный","вкусный","невкусный",
    "свежий","испорченный","горячий","холодный","тёплый","прохладный","жаркий","морозный","пасмурный",
    "солнечный","ветреный","тихий","спокойный","бурный","штормовой","грозовой","радужный","туманный",
    "ясный","здоровый","больной","сильный","слабый","богатый","бедный","умный","глупый","красивый",
    "уродливый","высокий","низкий","широкий","узкий","длинный","короткий","глубокий","мелкий","толстый",
    "тонкий","тяжёлый","лёгкий","твёрдый","мягкий","гладкий","шершавый","липкий","скользкий","острый",
    "тупой","быстрый","медленный","ранний","поздний","древний","современный","новый","старый","молодой",
    "пожилой","взрослый","детский","золотой","серебряный","медный","железный","деревянный","стеклянный",
    "пластиковый","бумажный","тканевый","кожаный","резиновый","каменный","кирпичный","бетонный","пустой",
    "полный","открытый","закрытый","свободный","занятой","чистый","грязный","ровный","кривой","прямой",
    "изогнутый","острый","тупой","главный","второстепенный","важный","неважный","нужный","ненужный",
    "полезный","вредный","интересный","скучный","весёлый","грустный","счастливый","несчастный","добрый",
    "злой","ласковый","грубый","вежливый","невежливый","честный","лживый","трудолюбивый","ленивый"
  ]
};

const DEV_WORDS = [
  // JavaScript Basics
  "function","const","let","var","return","if","else","for","while","do","switch","case","break",
  "continue","default","try","catch","finally","throw","new","this","typeof","instanceof","delete",
  "void","in","of","class","extends","super","constructor","static","get","set","yield","await",
  "async","export","import","default","from","as","null","undefined","true","false","NaN","Infinity",
  
  // Array Methods
  "map","filter","reduce","forEach","find","findIndex","some","every","includes","indexOf","lastIndexOf",
  "slice","splice","concat","join","reverse","sort","push","pop","shift","unshift","flat","flatMap",
  "keys","values","entries","from","isArray","of","fill","copyWithin",
  
  // Object Methods
  "keys","values","entries","assign","create","defineProperty","defineProperties","freeze","seal",
  "preventExtensions","isFrozen","isSealed","isExtensible","getOwnPropertyDescriptor","getOwnPropertyDescriptors",
  "getPrototypeOf","setPrototypeOf","hasOwn","propertyIsEnumerable","toString","valueOf",
  
  // String Methods
  "charAt","charCodeAt","codePointAt","concat","includes","endsWith","startsWith","indexOf","lastIndexOf",
  "localeCompare","match","matchAll","normalize","padEnd","padStart","repeat","replace","replaceAll",
  "search","slice","split","substring","toLowerCase","toUpperCase","trim","trimStart","trimEnd",
  
  // Number Methods
  "toFixed","toPrecision","toExponential","isNaN","isFinite","isInteger","isSafeInteger","parseInt",
  "parseFloat",
  
  // Math
  "Math","abs","ceil","floor","round","max","min","pow","sqrt","cbrt","hypot","random","sin","cos",
  "tan","asin","acos","atan","atan2","log","log10","log2","exp","expm1","sinh","cosh","tanh","PI","E",
  
  // Date
  "getFullYear","getMonth","getDate","getDay","getHours","getMinutes","getSeconds","getMilliseconds",
  "setFullYear","setMonth","setDate","setHours","setMinutes","setSeconds","setMilliseconds","toISOString",
  "toJSON","toDateString","toTimeString","toLocaleString","getTime","setTime","now","UTC","parse",
  
  // Promise
  "Promise","resolve","reject","then","catch","finally","all","allSettled","race","any",
  
  // React
  "useState","useEffect","useContext","useReducer","useCallback","useMemo","useRef","useImperativeHandle",
  "useLayoutEffect","useDebugValue","useDeferredValue","useTransition","useId","createContext","createRef",
  "forwardRef","memo","lazy","Suspense","Fragment","StrictMode","Profiler","createRoot","hydrateRoot",
  "render","createElement","cloneElement","isValidElement","Children","Component","PureComponent",
  
  // CSS Properties
  "transform","translateX","translateY","translateZ","scale","scaleX","scaleY","scaleZ","rotate","rotateX",
  "rotateY","rotateZ","skew","skewX","skewY","matrix","matrix3d","perspective","opacity","color",
  "backgroundColor","backgroundImage","backgroundPosition","backgroundSize","backgroundRepeat","border",
  "borderRadius","borderWidth","borderColor","borderStyle","boxShadow","textShadow","flex","grid",
  "alignItems","justifyContent","alignSelf","justifySelf","flexDirection","flexWrap","flexGrow","flexShrink",
  "flexBasis","order","gap","rowGap","columnGap","margin","padding","marginTop","marginRight","marginBottom",
  "marginLeft","paddingTop","paddingRight","paddingBottom","paddingLeft","display","position","top","left",
  "right","bottom","zIndex","width","height","maxWidth","maxHeight","minWidth","minHeight","overflow",
  "overflowX","overflowY","cursor","pointer","hover","focus","active","visited","link","before","after",
  
  // Web APIs
  "document","window","navigator","location","history","localStorage","sessionStorage","fetch","XMLHttpRequest",
  "addEventListener","removeEventListener","dispatchEvent","querySelector","querySelectorAll","getElementById",
  "getElementsByClassName","getElementsByTagName","createElement","createTextNode","appendChild","removeChild",
  "replaceChild","insertBefore","innerHTML","innerText","textContent","classList","style","setAttribute",
  "getAttribute","removeAttribute","hasAttribute","requestAnimationFrame","cancelAnimationFrame","setTimeout",
  "clearTimeout","setInterval","clearInterval","console","log","warn","error","info","table","clear","time",
  "timeEnd","group","groupEnd","JSON","parse","stringify","encodeURI","decodeURI","encodeURIComponent",
  "decodeURIComponent","btoa","atob",
  
  // TypeScript
  "type","interface","enum","namespace","module","declare","abstract","public","private","protected",
  "readonly","optional","any","unknown","never","void","null","undefined","boolean","number","string",
  "symbol","bigint","object","array","tuple","record","pick","omit","partial","required","readonly",
  "exclude","extract","nonnullable","returnType","instanceType","parameters","constructorParameters",
  
  // Node.js
  "require","module","exports","__dirname","__filename","process","Buffer","path","fs","http","https",
  "net","stream","events","util","child_process","os","crypto","zlib","dns","url","querystring"
];

const QUOTES = {
  en: [
    "The only way to do great work is to love what you do.",
    "In the middle of every difficulty lies opportunity.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is not final, failure is not fatal it is the courage to continue that counts.",
    "Believe you can and you are halfway there.",
    "You miss one hundred percent of the shots you don't take.",
    "I have not failed I have just found ten thousand ways that won't work.",
    "The best time to plant a tree was twenty years ago the second best time is now.",
    "A person who never made a mistake never tried anything new.",
    "Education is the most powerful weapon which you can use to change the world.",
    "Do what you can with what you have where you are.",
    "Everything you have ever wanted is on the other side of fear.",
    "Life is what happens when you are busy making other plans.",
    "The unexamined life is not worth living.",
    "Turn your wounds into wisdom.",
    "Be the change that you wish to see in the world.",
    "Imagination is more important than knowledge.",
    "The journey of a thousand miles begins with one step.",
    "That which does not kill us makes us stronger.",
    "Your time is limited don't waste it living someone else's life.",
    "Stay hungry stay foolish.",
    "Simplicity is the ultimate sophistication.",
    "Quality is not an act it is a habit.",
    "Well done is better than well said.",
    "Hard work beats talent when talent doesn't work hard.",
    "Fall seven times and stand up eight.",
    "The only disability in life is a bad attitude.",
    "Strive not to be a success but rather to be of value.",
    "The expert in anything was once a beginner.",
    "Dream big and dare to fail.",
    "Nothing is impossible the word itself says I am possible.",
    "You are braver than you believe stronger than you seem.",
    "All our dreams can come true if we have the courage to pursue them.",
    "Do not let what you cannot do interfere with what you can do.",
    "You can't use up creativity the more you use the more you have.",
    "Start where you are Use what you have Do what you can.",
    "Don't wait The time will never be just right.",
    "Excellence is not a skill it is an attitude.",
    "Life is either a daring adventure or nothing at all.",
    "Happiness is not something you postpone for the future.",
    "The secret of happiness is freedom the secret of freedom is courage.",
    "We become what we think about.",
    "What we think we become.",
    "Change your thoughts and you change your world."
  ],
  
  uz: [
    "Bilim eng katta boylikdir uni hech kim sendan tortib ololmaydi.",
    "Har bir katta maqsad kichik qadamdan boshlanadi.",
    "Muvaffaqiyatsizlik bu muvaffaqiyatga olib boruvchi yoldagi bir bekat.",
    "Kelajak oz orzulariga ishonganlarga tegishlidir.",
    "Har bir kun yangi imkoniyatlar eshigini ochadi.",
    "Oqish va organish hech qachon kech emas.",
    "Dunyoni ozgartirish uchun avval ozingni ozgartir.",
    "Vaqt eng qimmatli boylikdir uni bekorga sarflamang.",
    "Dostlik va birodarlik eng ulug qadriyatlardandir.",
    "Mehnatsevarlik har qanday muvaffaqiyatning asosidir.",
    "Yaxshilik qilishdan hech qachon charchamang.",
    "Haqiqiy baxt ozgalarni baxtli qilishdadir.",
    "Har qanday qiyinchilik ortida yengillik bordir.",
    "Ilm olish beshikdan qabrgacha farzdir.",
    "Sabr qilgan kishi murodiga yetadi.",
    "Ota-onani hurmat qilish farzandlik burchidir.",
    "Soglom tanda soglom aql boladi.",
    "Kamtarlik insonni uluglaydi.",
    "Har bir ishning oz vaqti bor.",
    "Inson qadri uning bilimi va xulqi bilan olchanadi.",
    "Buyuk ishlar kichik harakatlardan boshlanadi.",
    "Til millatning ruhi uni asrash har bir fuqaroning burchidir.",
    "Yoshlar kelajak bunyodkorlaridir.",
    "Kuch birlikda baraka ahillikdadir.",
    "Mehnat rohatning asosidir.",
    "Aql oltindan qimmat bilim kumushdan aziz.",
    "Yaxshilik joyda qolmas daryo bo'lib oqar.",
    "Tori soz toshni yorar.",
    "Vatan onadek muqaddasdir.",
    "Dost achitib gapirar dushman kuldirib.",
    "Tinchlik eng katta ne'matdir.",
    "Achchiq tajriba eng yaxshi ustozdir.",
    "Har narsaning oz me'yori bor.",
    "Yaxshi niyat yarim davlatdir.",
    "Avval oyla keyin soyla.",
    "Odamni kiyimi emas bilimi bezaydi.",
    "Mehnat qilsang rohat korasan.",
    "Saxiylik boylikning ziynatidir.",
    "Qanoat tuganmas xazinadir.",
    "Kup oqigan kup biladi.",
    "Aql yoshda emas boshdadir.",
    "Keksani hurmat qil yoshni izzat qil.",
    "Harakatda barakat bor.",
    "Bugungi ishni ertaga qoyma.",
    "Tirishqoqlik togni yorar.",
    "Gayrat bilan ish bitar.",
    "Ilmli kishi hurmat topadi.",
    "Bilim sirlarni ochuvchi kalitdir.",
    "Organgan ilmni yashirgan jabr qilgan boladi.",
    "Bilganini orgatmoq savobdir."
  ],
  
  ru: [
    "Знание сила.",
    "Учиться никогда не поздно.",
    "Терпение и труд всё перетрут.",
    "Век живи век учись.",
    "Утро вечера мудренее.",
    "Семь раз отмерь один раз отрежь.",
    "Под лежачий камень вода не течёт.",
    "Без труда не вытащишь и рыбку из пруда.",
    "Что посеешь то и пожнёшь.",
    "Лучше поздно чем никогда.",
    "Делу время потехе час.",
    "Слово не воробей вылетит не поймаешь.",
    "В гостях хорошо а дома лучше.",
    "Друзья познаются в беде.",
    "Кто не рискует тот не пьёт шампанское.",
    "Всё что ни делается всё к лучшему.",
    "Не имей сто рублей а имей сто друзей.",
    "Готовь сани летом а телегу зимой.",
    "Дарёному коню в зубы не смотрят.",
    "Дважды в одну реку не войдёшь.",
    "Лучше синица в руках чем журавль в небе.",
    "Молчание золото.",
    "Не рой другому яму сам в неё попадёшь.",
    "Смелость города берёт.",
    "Один за всех и все за одного.",
    "Правда глаза колет.",
    "Доверяй но проверяй.",
    "С кем поведёшься от того и наберёшься.",
    "Кто рано встаёт тому бог подаёт.",
    "Куй железо пока горячо.",
    "Время деньги.",
    "Всё тайное становится явным.",
    "Дело мастера боится.",
    "Труд человека кормит а лень портит.",
    "Тяжело в ученье легко в бою.",
    "Старый друг лучше новых двух.",
    "Мир не без добрых людей.",
    "Скромность украшает человека.",
    "Совесть лучший советчик.",
    "Счастье это когда тебя понимают.",
    "Родина мать умей за неё постоять.",
    "Хочешь жить умей вертеться.",
    "Береги платье снову а честь смолоду.",
    "Не так страшен чёрт как его малюют.",
    "От добра добра не ищут.",
    "Жизнь прожить не поле перейти.",
    "Наука хлеба не просит а хлеб даёт.",
    "Книга лучший подарок.",
    "Грамоте учиться всегда пригодится.",
    "Доброе дело само себя хвалит."
  ]
};

const SOUNDS = {
  blue: { freq: 800, dur: 0.03, type: 'sine', errFreq: 200, name: 'Blue Switch' },
  brown: { freq: 600, dur: 0.04, type: 'triangle', errFreq: 180, name: 'Brown Switch' },
  red: { freq: 1000, dur: 0.02, type: 'square', errFreq: 220, name: 'Red Switch' },
  creamy: { freq: 500, dur: 0.05, type: 'sine', errFreq: 150, name: 'Creamy' },
  thock: { freq: 300, dur: 0.06, type: 'sawtooth', errFreq: 120, name: 'Thock' }
};

const RANKS = [
  { name: "Boshlangich", min: 0, stars: 1, next: 20, color: "#808080", icon: "🌱" },
  { name: "Organuvchi", min: 20, stars: 2, next: 40, color: "#4ec9a0", icon: "📖" },
  { name: "Ortacha", min: 40, stars: 2, next: 60, color: "#7eb8f7", icon: "⚡" },
  { name: "Mohir", min: 60, stars: 3, next: 80, color: "#b89ef7", icon: "🔥" },
  { name: "Ustoz", min: 80, stars: 4, next: 100, color: "#e2b714", icon: "👑" },
  { name: "Ekspert", min: 100, stars: 4, next: 120, color: "#ff9060", icon: "💎" },
  { name: "Master", min: 120, stars: 5, next: 150, color: "#ff3355", icon: "🏆" },
  { name: "Legend", min: 150, stars: 5, next: null, color: "#ffd700", icon: "⭐" }
];

console.log('MR TYPE - Word pools loaded:', {
  en: WORD_POOLS.en.length,
  uz: WORD_POOLS.uz.length,
  ru: WORD_POOLS.ru.length,
  dev: DEV_WORDS.length,
  quotes: {
    en: QUOTES.en.length,
    uz: QUOTES.uz.length,
    ru: QUOTES.ru.length
  }
});
